#!/bin/sh

cd /tmp
rm -f hosts.[0-9]*

cat << __EOF | while read LIST; do COUNT=$(( ${COUNT} + 1 )); curl -g "${LIST}" | sed -e s/$'\r'//g 1> /tmp/hosts.${COUNT}; done
http://adaway.org/hosts.txt
http://netcologne.dl.sourceforge.net/project/adzhosts/FORADAWAY.txt
http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext
http://someonewhocares.org/hosts/hosts
http://winhelp2002.mvps.org/hosts.txt
http://www.malwaredomainlist.com/hostslist/hosts.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
__EOF

cat /tmp/hosts.[0-9]* \
  | grep -v '^#' \
  | grep -v '^$' \
  | awk '{print $2}' \
  | sort -u -f \
  | while read I
    do
      echo 0.0.0.0 ${I}
    done | sed 1d 1> /tmp/hosts
	for i in `cat /Users/gtsewell77/hostsupdate/GTShostsUpdate/whitelist`; 
		do grep -v $i /tmp/hosts > /tmp/hoststemp; mv /tmp/hoststemp /tmp/hosts
	done

    sh -c 'cat /Users/gtsewell77/hostsupdate/GTShostsUpdate/myhosts /tmp/hosts > /tmp/hosts.merge'; mv /tmp/hosts.merge /tmp/hosts

# copy / overwrite the hosts file at /etc/hosts

cp /tmp/hosts /etc/hosts

# =========================================================
# need at end to have the hosts flushed and service restarted

# for mac
sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder

# for unix and others

# Debian/Ubuntu 
# sudo /etc/rc.d/init.d/nscd restart

#Linux with systemd: 
# sudo systemctl restart network.service

#Fedora Linux: 
# sudo systemctl restart NetworkManager.service

#Arch Linux/Manjaro with Network Manager: 
# sudo systemctl restart NetworkManager.service

#Arch Linux/Manjaro with Wicd: 
# sudo systemctl restart wicd.service
